### Admin Auth Login
POST {{host}}/admin/login
Content-Type: application/json
Origin: {{host}}

{
  "username": "Kivie",
  "password": "123456"
}
> {% client.global.set("access_token", response.body.access_token); %}

### Admin Auth Register
POST {{host}}/admin/register
Content-Type: application/json
Origin: {{host}}

{
  "username": "Kivie",
  "password": "123456"
}

### Admin Auth Profile
GET {{host}}/admin/profile
Accept: application/json
Origin: {{host}}
Authorization: Bearer {{access_token}}

### Admin Auth Logout
DELETE {{host}}/admin/logout
Content-Type: application/json
Origin: {{host}}
Authorization: Bearer {{access_token}}
